### ISSUE TITLE
Log in, log out, log in takes you to the edX dashboard

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#102]
### Steps to Reproduce

- Sign in to MITx Online: https://rc.mitxonline.mit.edu/signin/
- Note: You are sent to https://rc.mitxonline.mit.edu/
- Sign out 
- Immediately sign back in
- Note: You are sent to the edX dashboard: https://lms-qa.mitxonline.mit.edu/dashboard

### Expected Behavior

You should be taken to the home page for MITx Online: https://rc.mitxonline.mit.edu/
The behavior should be the same as when you initially log in

### Related Issues

We had a similar issue in xPRO. Check out:
- https://github.com/mitodl/mitxpro/pull/2103
- https://github.com/mitodl/mitxpro/issues/1931

**Comment by arslanashraf7** [comment]
FYI, 

I believe this issue has two parts that include the redirection related problem:

1. Sign into `MITxOnline(https://rc.mitxonline.mit.edu/signin/)` -> `Sign Out` -> `Sign in again` --- You will be redirected to the `LMS dashboard( https://lms-qa.mitxonline.mit.edu/dashboard)` instead of MITxOnline's dashboard.
2. Sign into LMS( https://lms-qa.mitxonline.mit.edu/) -> `Sign Out` -> (Here you will be redirected to [MITxOnline](https://rc.mitxonline.mit.edu) for authentication -> `Sign In Again` You will be redirected to LMS's dashboard.

**To fix Point # 1:**
- We need to update https://github.com/mitodl/edx-platform to at least [this commit](https://github.com/edx/edx-platform/commit/4a2549f49af44c12f03d957190948800f8614450) from the upstream `edx-platform` master. We can either cherry-pick the commit into our master with edX's.
- We will need to add MITxOnline's domain in the `LOGIN_REDIRECT_WHITELIST` env variable. For RC it would be something like `rc.mitxonline.mit.edu` or `mitxonline-rc.mitxonline.mit.edu`.

@mitodl/devops (Would there be anything in the above point for devs ?)

I tested the above fix locally and it works.

**To fix Point # 2:**
- We take https://github.com/mitodl/edx-platform/pull/241 PR to upstream (What this PR basically does is that it defined a default value of REDIRECT_URL in edX to be used as a default redirect in case of logout, the default URL for redirect is currently `/` which eventually takes the user to `/dashboard` that takes the user to the Auth Provider's login page with LMS's `/dashboard` redirect added in the URL, so when the user sign's in it takes them to LMS's dashboard).
- Another fix could be tweaking our own theme since we aren't sure how useful is this feature for edX users to use some other URL instead of the current default `/` as a logout redirect. So for now I'll be putting up a PR in [MITxOnline Theme](https://github.com/mitodl/mitxonline-theme) as an available option.


CC: @pdpinch, @briangrossman

**Comment by blarghmatey** [comment]
So, we are currently building against the upstream edx/edx-platform repository for the instances that we are deploying so that commit should already be present. I just added the marketing site to the LOGIN_REDIRECT_WHITELIST.

**Comment by arslanashraf7** [comment]
> So, we are currently building against the upstream edx/edx-platform repository for the instances that we are deploying so that commit should already be present. I just added the marketing site to the LOGIN_REDIRECT_WHITELIST.

@blarghmatey Can you confirm the URL of the domain you added in the `LOGIN_REDIRECT_WHITELIST` is it `mitxonline-rc.mitxonline.mit.edu` or `rc.mitxonline.mit.edu`?

In case it's `rc.mitxonline.mit.edu`, is it possible that we could add `mitxonline-rc.mitxonline.mit.edu` instead or both? The reason for this is that the logout URL hit by MITxOnline is always `https://courses-qa.mitxonline.mit.edu/logout?redirect_url=https%3A%2F%2Fmitxonline-rc.mitxonline.mit.edu` either we access the MITx app on `rc.` or `mitxonline-rc.`.

As a note, the `redirect_url` that our web app e.g. MITxOnline adds on the LMS while logout basically comes from this config variable `MITX_ONLINE_BASE_URL` from our webapp which I suppose is set to `https://mitxonline-rc.mitxonline.mit.edu` for both `rc.` and `mitxonline-rc` instances.

**Comment by blarghmatey** [comment]
I just updated the OAuth config to use `rc.` which should resolve that problem.

**Comment by blarghmatey** [comment]
This has been resolved in QA and production.
