### ISSUE TITLE
Enrolled button on about page links to course before it has started 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1036]
### Steps to Reproduce

1. set up a course with an enrollment date in the past and a start date in the future
2. enroll yourself in it (should work fine, because it’s open for enrollment) 
3. On the about page, the “enroll” button changes to “enrolled”
4. Click “enrolled”

### Expected Behavior

- the button should be disabled. You can't view the course yet because it hasn't started. 

### Actual Behavior

- The button is active
- It links to open edX LMS, which I think will redirect back to the dashboard, which is confusing

**Comment by collinpreston** [comment]
@pdpinch here are two screenshots that show an additional message informing the user that they are indeed enrolled in the course, but the button is not active because the course has not begun.  The difference between the two screenshots are that one shows the text in the button as grey and the other shows the text in the button as red.  Let me know which you prefer.
<img width="962" alt="Screen Shot 2022-09-23 at 11 00 05" src="https://user-images.githubusercontent.com/8311573/191991571-3f140b0c-a304-476d-9824-8219c2d01900.png">
<img width="962" alt="Screen Shot 2022-09-23 at 10 59 35" src="https://user-images.githubusercontent.com/8311573/191991575-6d7cd94f-2f1b-490b-91c1-b54b9bf914b5.png">

**Comment by pdpinch** [comment]
The button is inactive, right? I prefer the first one where the button text is gray.
