### ISSUE TITLE
Run legacy data migrations in production 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1053]
Blocked until 

- [x] #1035 
- [x] #1030 
- [x] #960 
- [x] #961 

#### Acceptance Criteria:

- [ ] plan for when we want this data exposed to users. What is the customer support impact?
- [ ] do some offline tests to estimate how long it will take to run in production 
- [ ] decide on day / time to run so we don't interfere with any other site process 

Run these migrations in production (@rachellougee please review & add the specific management commands):

- [ ] product import
   - To create **active** products for DEDP courses with price 1000, run ```python manage.py create_product_for_program_courses --active``` 
- [ ] enrollment import
    -  Run a command like ```python manage.py import_micromasters_data```. This will run and import the course runs/financial aid/order/grades
- [ ] grades import 
    -  The above command covers it, it doesn't need to run separately

#### out of scope

- program enrollments #703 
- course certificates #705 
- program certificates #706

**Comment by rachellougee** [comment]
I've added the commands we need to run on production. I will update if anything changes

**Comment by rachellougee** [comment]
@pdpinch Should we run product import for the DEDP program as active or inactive? https://github.com/mitodl/mitxonline/issues/1035 is deployed, but I am not entirely sure about the impact of creating active products for all DEDP courses including the imported course run from MM
tagging @jkachel in case he knows the impact

**Comment by pdpinch** [comment]
We want to run product import with the DEDP program as active, but we need to close https://github.com/mitodl/mitxonline/issues/1035 first.

**Comment by rachellougee** [comment]
My plan to run legacy migration on production on Monday 10/03 is like this:

**Before running migration**
1. Let @blarghmatey know before running it so he can take a snapshot of MITxOnline
2. Run queries to capture the COUNT/MAX(id) against the following tables on BI
   (It's not going to be 100% accurate as data can come in anytime, but a general idea of the current state of these tables)
 ``` 
 SELECT COUNT(*) FROM public.courses_courserun;  --57 as of 09/30
 SELECT MAX(id) FROM public.courses_courserun;  
 
 SELECT COUNT(*) FROM public.courses_courserunenrollment; --61129 as of 09/30
 SELECT MAX(id) FROM public.courses_courserunenrollment; 
 
 SELECT COUNT(*) FROM public.flexiblepricing_flexibleprice; --1 as of 09/30
 SELECT MAX(id) FROM public.flexiblepricing_flexibleprice;  
 
 SELECT COUNT(*) FROM public.ecommerce_order; --20 as of 09/30
 SELECT MAX(id) FROM public.ecommerce_order;  
 
 SELECT COUNT(*) FROM public.ecommerce_line; --20 as of 09/30
 SELECT MAX(id) FROM public.ecommerce_line;  
 
 SELECT COUNT(*) FROM public.ecommerce_transaction; --9 as of 09/30
 SELECT MAX(id) FROM public.ecommerce_transaction;  
 
 SELECT COUNT(*) FROM public.courses_courserungrade; --23021 as of 09/30
 SELECT MAX(id) FROM public.courses_courserungrade;  
```
3. I will also take a dump of the above-specific tables in case

**Running migration**
1. Run the management command to create active products for _existing_ DEDP courses
     ```python manage.py create_product_for_program_courses --active```
2. Run the import command to bring in the CourseRun, Enrollment, Order/Line/Transaction, FinancialAid, and Grades data from MicroMaster
    ```python manage.py import_micromasters_data```
3.  Run ```create_product_for_program_courses``` command again to generate products for those _migrated_ CourseRuns from the above step 

4. (optional) run ```import_micromasters_data``` again to make sure Order/Line/Transaction for those imported course runs are brought over. (Or it can wait until 10/07 to run the import again)

No matter what sequence we run for product and MM data migration, it's going to be multi-steps because we need to generate products for the newly imported course runs, and Order/Line are depending on products


I've also done an offline test against the production database Tobias created in #1013,  the MM import queries take about 37 sec, not sure what the best time to run it when the traffic is relative low?
> do some offline tests to estimate how long it will take to run in production

@pdpinch @rhysyngsun FYI. Feel free to correct me if anything missing here

**Comment by rachellougee** [comment]
Created products and Ran data migration on 10/04. Here are results for reference.
```
002_import_courserun.sql
Rows added: 82

003_import_enrollment.sql
Rows added: 5230

004_import_financial_aid.sql
Rows added: 6545

005_import_order.sql
Rows added: 10162

006_import_line.sql
Rows added: 10162

007_import_transation.sql
Rows added: 9353

008_import_combined_final_grade.sql
Rows added: 5498
```

Table | COUNT/MAX(ID) Before | COUNT/MAX(ID) After 
-- | -- | --
courses_courserun | 58/59 | 140/141
courses_courserunenrollment | 62649/62651 | 67893/77771 
flexiblepricing_flexibleprice | 1/1 | 6374/6547
ecommerce_order | 20/20 |  10182/10182
ecommerce_line |  20/20 |  10182/13316
ecommerce_transaction | 9/11 |  9362/9364
courses_courserungrade | 24607/24607 | 30105/30115

**Comment by rachellougee** [comment]
Data migration run on 10/11

002_import_courserun.sql
Rows added/updated: 0

003_import_enrollment.sql
Rows added/updated: 13

004_import_financial_aid.sql
Rows added/updated: 53

005_import_order.sql
Rows added/updated: 363

Running: 006_import_line.sql
Rows added/updated: 364

007_import_transation.sql
Rows added/updated: 345

008_import_combined_final_grade.sql
Rows added/updated: 10

Removed one extra line in https://github.com/mitodl/mitxonline/issues/1125
