### ISSUE TITLE
"Unknown Error" when cancelling a Cybersource card order

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1113]
### Steps to Reproduce

1. in production, put a course in your cart
2. Click the order button to advance to Cybersource
3. Click the cancel link in Cybersource

### Expected Behavior

- Return to the mitxonline site with banner acknowledging that you canceled your order 

### Actual Behavior

- Return to the mixonline site with a banner saying "an unknown error occurred" 
- couldn't find a corresponding error log in sentry 

### Related Issues

- Looking at the settings in Cybersource it appears that we haven't set a URL for cancels: 

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/430126/194876873-cc8a68d0-dad3-493a-b407-5c29c332c596.png">

### Screenshot or Screencast

<img width="1713" alt="image" src="https://user-images.githubusercontent.com/430126/194876920-69438f1e-9001-4925-8e93-81bbe765c38b.png">

**Comment by jkachel** [comment]
This may have been fixed in #1116 - since the cancel would go through CyberSource first, it was probably hitting the callback and you were getting the Unknown Error (i.e. it fell out the bottom) because the status on the order wasn't `PENDING` anymore. We fixed that for payment but it's the same issue here so this now appears to work OK.

**Comment by pdpinch** [comment]
Do you think we can close this? Or should we do some more testing?

**Comment by jkachel** [comment]
I'm closing this - it's pretty old and in testing just now this worked as expected.
