### ISSUE TITLE
OVS: Support for downloadable videos

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1183]
As a learner, I'd like to be able to download videos for later playback. Some learners can't reliably access streams in their country, but they can download videos. 

As a course author, I'd like the videos I upload into OVS to include downloadable versions when they are posted into open edX studio. 

#### Acceptance Criteria:

- [x] research current video encodings on [OVS](https://github.com/mitodl/odl-video-service/). Do we create a file suitable for download?
- [ ] research the Studio video API. What changes need to be made to OVS to support posting download URLs as well as streams?
- [ ] open a discussion post with the plan for supporting downloadable videos 
- [ ] Open issue(s) in [OVS](https://github.com/mitodl/odl-video-service/issues) as necessary

**Comment by collinpreston** [comment]
@pdpinch some questions and notes I have prior to creating any OVS issues or HQ RFC.

1. Once someone has uploaded a video to OVS through Dropbox and the video is transcoded HLS format, how does the Admin know the video ID to use when adding the video to a course through edX Studio?
2. What format and video quality do we want to offer as a download?
3. There is currently a bug in edX studio when you add a HLS and MP4 videos to a course component and enable downloading.  The link to download the MP4 formatted video does not display.  Once this is fixed we should have no problem with specifying a second video URL (MP4 formatted video URL) in addition to the HLS URL when calling the edX Studio video API.  (assuming we intend to use MP4 for the downloadable videos).

**Comment by collinpreston** [comment]
Based from my initial understanding, here is an assessment of functionality and associated changes we will need to make in order to add support for this issue:

**Call sequence when someone uploads a video to DropBox:**
Post video to Dropbox
↓
Upload Videos From Dropbox :post() 
↓
api.process_dropbox_data()
↓
Video() and Videofile() are created for original
↓
stream-to-S3()
↓
transcode_from_s3()
↓
transcode_video()
↓
Video Transcode (this is aws)

*Continuous task*
update video_statuses()
↓
refresh-status()
↓
Process_transcode_results()
↓
add_hls_to_edx()
↓
Post_hls_to_edx()
↓
Post_hps_to_edx()
↓
Videofile.can_add_to_edx()
↓
Post to edu endpoint 

**Changes that need to be made**

1. Create an S3 location for MP4 videos
2. Update AWS elastic encoder preset to produce an MP4 video.
3. Update `transcode_video` to allow a developer to define whether they want MP4 and HLS output or just HLS output.  This function is used by Dropbox uploads as well as lecture uploads (which I assume we don't need to create MP4 videos for).  This file should also 
4. Update `process_transcode_results` to handle MP4.
5. Update `can_add_to_edx` to account for MP4 files. 
6. Update `post_hls_to_edx` to send a request containing the HLS and encoded MP4 files to edx.  Keep in mind that we don't want to send the original video file to edx, so change 5 should be considered.  There is a task and method that share the name `post_hls_to_edx` and both should be updated.  Right now the call (shown in the sequence above) to this method is made after a VideoFile is saved.  Since there will be multiple video files, it may be better to trigger this call when the VideoStatus is changed to `COMPLETE` which is done after the transcode results are processed and the VideoFile(s) are saved (https://github.com/mitodl/odl-video-service/blob/5c432b6c4f83b3394a89b00bc46ffb845921ebd5/cloudsync/api.py#L128).

**Comment by Ferdi** [comment]
@collinpreston can you create a visual diagram of the architecture you describe above ?

**Comment by mbertrand** [comment]
1. I think the file can probably go in the same bucket path as other transcoded videos: https://github.com/mitodl/odl-video-service/blob/master/ui/models.py#L454-L458

On a related note though, I noticed that the `cloudsync.api.transcode_video` function assumes every transcoded output is an HLS format requiring a playlist, so that will have to change: https://github.com/mitodl/odl-video-service/blob/master/cloudsync/api.py#L178-L184

**Comment by collinpreston** [comment]
[OVS Dropbox upload (current).pdf](https://github.com/mitodl/mitxonline/files/10075584/OVS.Dropbox.upload.current.pdf)
PDF of the swim lane diagram

**Comment by collinpreston** [comment]
Closing this issue since the PR in OVS has been merged: https://github.com/mitodl/odl-video-service/pull/1011
