### ISSUE TITLE
Allow course team to specify date for certificates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1257]
As an instructor, I need more time between when my course ends and when I'm ready for certificates to be created. I use this time to review and adjust grades, and to review any proctored exams that were flagged. 

#### Acceptance Criteria:

- [ ] Research how to turn on the "Certificates Display Behavior" and "Certificates Available Date" settings in Studio (it's not available on studio.mitxonline.mit.edu, but it is available on studio.edx.org 

**Syncing Steps**
- [ ] Sync the certificates available date from Studio to the mitxonline app
- [ ] Create certificates after the certificates available date, instead of after the course end date. 

The above criteria acceptance might be divided into a couple of PRs as mentioned below (Orderly):

1. A PR in MITxOnline to add the `certificate_available_date` field, and change all the certificate generation logic from `end_date` to `certificate_available_date`. (This enables us to add certificate available date manually until we have our PR merged in edX. Already in progress WIP-https://github.com/mitodl/mitxonline/pull/1286)
2. An upstream PR to edX to include `certificate_available_date` to course details API.
3. A PR in [edx-api-client](https://github.com/mitodl/edx-api-client) to enable fetching `certificate_available_date` in conjunction with another PR in MITxOnline that uses this edx-api-client and syncs the `certificate_available_date` from edX.

**Comment by arslanashraf7** [comment]
Update:

So I was looking around this and this is what I've got.

>Research how to turn on the "Certificates Display Behavior" and "Certificates Available Date" settings in Studio (it's not available on studio.mitxonline.mit.edu, but it is available on studio.edx.org

To enable the Certificate's display behavior and certificate available dates we need to do the following:
1. Add a waffle switch in `admin/waffle/switch/1/change/` with value `http://localhost:18000/admin/waffle/switch/1/change/`  ([Ref](https://github.com/openedx/edx-platform/blob/master/lms/djangoapps/certificates/config.py#L11) from edX).
2. Add a Django setting/feature in CMS's `FEATURES` dictionary `"ENABLE_V2_CERT_DISPLAY_SETTINGS": True`. ([Ref](https://github.com/openedx/edx-platform/blob/master/cms/envs/common.py#L472) from edX).

After the above steps, the certificate display behavior and date options should be visible in `studio`>`your course`>`Settings`>`Schedule & Details`.


> Sync the certificates available date from Studio to the mitxonline app

For this, we need an API from edX to provide the details, while looking around I found two APIs only that send this value in the response:
1.  [Course Outline API](https://courses.edx.org/api-docs/#/course_home/course_home_v1_outline_read) needs an enrolled user.
2. [Course Progress API](https://courses.edx.org/api-docs/#/course_home/course_home_progress_read) needs an enrolled user.
3. [Courseware API](https://courses.edx.org/api-docs/#/courseware/courseware_course_read) needs an enrolled user.


The problem with the above APIs is that they need an enrolled user for the certificate details and we will need to call the APIs independent of enrollment. Turns out we can't use the above APIs.


> Create certificates after the certificates available date, instead of after the course end date.

Keeping the current possibilities in mind, I think we can divide this into two possible parts:

1. Add a new field(`certificate_available_date`) in MITxOnline, and change our certificate generation flow to follow this value instead of end_date. e.g. if `certificate_available_date` is available, use this, otherwise use `end_date`. Create the PR and get it running. This will enable us to at least set this value manually and use it.
2. Create an upstream PR that adds the `certificate_available_date` in the [course details API](https://courses.edx.org/api-docs/#/courses/courses_v1_courses_read). Probably, get it merged, and backport it too so that we can use it in our current edX instances.

@pdpinch FYI. Let me know your thoughts on this.

**Comment by arslanashraf7** [comment]
Update:

So this is probably going to be divided into a couple of PRs(Issues) based on the above comment.

1. A PR in MITxOnline to add the `certificate_available_date` field, and change all the certificate generation logic from `end_date` to `certificate_available_date`. (This enables us to add certificate available date manually untill we have our PR merged in edX. Already in progress WIP-https://github.com/mitodl/mitxonline/pull/1286)
2. An upstream PR to edx to include `certificate_available_date` to course details API.
3. A PR in [edx-api-client](https://github.com/mitodl/edx-api-client) to enable fetching `certificate_available_date` in conjunction with another PR in MITxOnline that uses this edx-api-client and syncs the `certificate_available_date` from edX.

Steps 1 & 3 can be done independently as mentioned, but we can also first do step#2 and then do steps 1 & 3 together. This might take some time since this required the edX PR to get merged first and probably backported to Olive.

**Comment by pdpinch** [comment]
That sounds correct to me @arslanashraf7. Can you update the description of this issue to reflect all the necessary steps and sequence? Thanks for starting on #1. I'm not quite ready to start working on the other steps.

**Comment by pdpinch** [comment]
> To enable the Certificate's display behavior and certificate available dates we need to do the following:
>
>    Add a waffle switch in admin/waffle/switch/1/change/ with value http://localhost:18000/admin/waffle/switch/1/change/ ([Ref](https://github.com/openedx/edx-platform/blob/master/lms/djangoapps/certificates/config.py#L11) from edX).
>    Add a Django setting/feature in CMS's FEATURES dictionary "ENABLE_V2_CERT_DISPLAY_SETTINGS": True. ([Ref](https://github.com/openedx/edx-platform/blob/master/cms/envs/common.py#L472) from edX).

Does either of these steps require deploying the [credentials application](https://github.com/openedx/credentials) or any other apps we may not be running in mitxonline?

**Comment by arslanashraf7** [comment]
> Does either of these steps require deploying the [credentials application](https://github.com/openedx/credentials) or any other apps we may not be running in mitxonline?

Thanks, That's a nice perspective to think about it, I tried and I was able to test certificate behavior locally without running the `credentials` service. And I couldn't find any specific service requirement in the docs that might suggest running a specific service for this.

I think we can try it out and see. I can open a PR in [ol-infrastructure](https://github.com/mitodl/ol-infrastructure), Let me know when you'd want that.

**Comment by pdpinch** [comment]
When I look at course in studio (e.g https://studio-qa.mitxonline.mit.edu/settings/details/course-v1:MITx+14.310x+3T2021) I don't see the fields for setting certificate_available_date. Is there a waffle flag of a setting that needs to be set?

**Comment by arslanashraf7** [comment]
> When I look at course in studio (e.g https://studio-qa.mitxonline.mit.edu/settings/details/course-v1:MITx+14.310x+3T2021) I don't see the fields for setting certificate_available_date. 

That might be because we haven't probably configured it there. 

>Is there a waffle flag of a setting that needs to be set?

Yes, we need to set a couple of things that I mentioned in [this comment](https://github.com/mitodl/mitxonline/issues/1257#issuecomment-1346463078) - Edited the comment a bit to be clearer and fixed a value. I can do these settings in the QA tomorrow, This will need a PR in https://github.com/mitodl/ol-infrastructure and a switch through Django Admin.

**Comment by arslanashraf7** [comment]
So, As per my last comment, I added the switch [here](https://courses-qa.mitxonline.mit.edu/admin/waffle/switch/5/change/). And the PR for enabling the feature flag for certificates display behaviour is at https://github.com/mitodl/ol-infrastructure/pull/1294.

**Comment by pdpinch** [comment]
I tried setting the waffle flag in production, but it didn't have the desired effect of letting me set the certificate generation date. Any idea what might be going wrong?

https://studio.mitxonline.mit.edu/admin/waffle_utils/waffleflagcourseoverridemodel/24/change/
https://studio.mitxonline.mit.edu/settings/details/course-v1:MITxT+14.310x+1T2023

**Comment by arslanashraf7** [comment]
This is working on RC though, e.g. take a look at https://studio-qa.mitxonline.mit.edu/settings/details/course-v1:Arbisoft+ARB_CRT_0001+2022_T1#schedule.

Maybe that's because I tested it there by setting the switch overall, e.g. https://studio-qa.mitxonline.mit.edu/admin/waffle/switch/.

I can try testing it by just setting an override instead of a switch itself.

**Comment by arslanashraf7** [comment]
Maybe that's because this is a switch and not a flag that's why the override isn't working, Are we looking to enable is just course wise?

**Comment by pdpinch** [comment]
Oh, I didn’t know that. 

We can turn it on for all courses. That’s OK.

**Comment by pdpinch** [comment]
That did it, thanks!

**Comment by pdpinch** [comment]
For the record, I set the switch in https://studio.mitxonline.mit.edu/admin/waffle/switch/4/change/
