### ISSUE TITLE
Dashboard: Don't display "course passed" tag before the course has ended 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1273]
### Steps to Reproduce

Not sure of all the steps, but a user in production reported the issue: https://odl.zendesk.com/agent/tickets/141848 -- let me know if you need access. 

This is for a course that is not self-paced, so it's not possible to pass it before the course ends and certificates have been generated. We do this to give the course team time to correct errors in assessments and adjust grades.  

### Expected Behavior

- Don't display the "course passed" tag until after the course has ended, or certificates have been generated (see in-progress issue https://github.com/mitodl/mitxonline/issues/1257)
- It might be helpful to include in the fix a management command to put a user into the correct state for testing (something like [alter_data in micromasters](https://github.com/mitodl/micromasters/blob/master/seed_data/management/commands/alter_data.py)) 

### Screenshot or Screencast

![PastedGraphic-1(1)](https://user-images.githubusercontent.com/430126/206733017-09b6c41f-0d2a-43a3-af58-07325a6e8d90.png)

**Comment by arslanashraf7** [comment]
This might have happened because we [sync the grades with a daily task](https://github.com/mitodl/mitxonline/blob/main/courses/api.py#L723) but generate the certificates only when the course end date has been reached in the case of non `self-paced` courses. So, Its possible that a user has passed grades but no certificate.

On the frontend, we check the [pass status through grades](https://github.com/mitodl/mitxonline/blob/main/frontend/public/src/lib/courseApi.js#L102) So if a user has a passing grade but has no certificate the `Course Passed` would show.

We can probably change our frontend logic to show this only when the user has a certificate(Something we do to show `View Certificate` button) instead of checking the passing grades, but is it possible for some courses to not have a certificate ever?

**Comment by pdpinch** [comment]
Thanks for the analysis. I think it's possible to "pass" a course in the audit track, so I don't think we can depend on the presence of a certificate. 

I think the logic should be:

1. If the course is self-paced, display "Course passed" if the learner has a passing grade, whenever that may be. 

2. If the course is _not_ self-paced, only display "Course Passed" if the course end date is in the past (and the course certificate date is in the past, when we implement #1257)

**Comment by arslanashraf7** [comment]
Closed via #1317
