### ISSUE TITLE
open edX: display user's full name instead of username in user menu

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#132]
In mitxonline-theme, we override the header template to display the user's full name instead of their username. We'd like to do the same thing with the MFEs that rely on `frontend-component-header-edx` 

#### Acceptance Criteria:

- [ ] fork `frontend-component-header-edx` into a repo named `frontend-component-header-mitxonline`
- [ ] update the user menu to display the user's full name, instead of their username
- [ ] work with DevOps to deploy the new component
- [ ] update the checklist if any additional steps are discovered

**Comment by asadiqbal08** [comment]
A question here, 
Did we use any react `frontend-component-*` defined by edx earlier somewhere as example ?

What I am expecting, 

1- We need to create a `PR` in our forked repo `frontend-component-header-mitxonline` with the requested user full name changes.
2- We need to utilize this `frontend-component-header-mitxonline` header component in our `edx-platform` fork to test it.

**Comment by pdpinch** [comment]
The dependency chain is complicated. In the browser, I see the UI we want to change when frontend-app-learning is loaded, but I haven't been able to find how that app includes the header component. 

It seems like the relevant code in frontend-component-header-edx is here: https://github.com/edx/frontend-component-header-edx/blob/4b69ab80e63ce6884851b475378057ce40ba0b24/src/Header.jsx#L143

**Comment by pdpinch** [comment]
There is a recent discussion on the open edX forums about how to fork the header, which may help:

https://discuss.openedx.org/t/mfe-header-override/5125

**Comment by asadiqbal08** [comment]
@pdpinch can you tell me about the point#2 ? I mean did we need to make any corresponding change in `https://github.com/mitodl/edx-platform`
I get the point what actual change is required to do in `frontend-component-header-edx` but I am thinking do we also need to integrate this react component in edx-platform to test it ?

**Comment by asadiqbal08** [comment]
@pdpinch  After looking around the MFE structure, it seems to me, we should try to push changes in upstream component otherwise we’ll have to maintain forks of relevant MFEs. 

Moreover, interesting fact is that the changes required in the corresponding ticket for showing the `user's full name` instead of `username` in [frontend-component-header-edx](https://github.com/edx/frontend-component-header-edx/blob/master/src/Header.jsx#L143) but in actual, it is fetching these information from another MFE that is [frontend-platform](https://github.com/edx/frontend-platform/blob/master/src/auth/AxiosJwtAuthService.js#L200-L216) that I believe not storing the `user’s full name` at the moment in `authUser` object.

For that, we need to add it in [frontend-platform HERE](https://github.com/edx/frontend-platform/blob/master/src/auth/AxiosJwtAuthService.js#L207) something like below:

```
name: decodedAccessToken.name,
family_name=decodedAccessToken.family_name,
given_name: decodedAccessToken.given_name
```
Code reference in [edX HERE](https://github.com/edx/edx-platform/blob/3152c14192dcccac79b7b7a76eba91b380eba78a/openedx/core/djangoapps/oauth_dispatch/jwt.py#L179-L193)

**Comment by pdpinch** [comment]
How do the Profile ([frontend-app-profile](https://github.com/edx/frontend-app-profile)) and Account ([fronted-app-account](https://github.com/edx/frontend-app-account)) MFEs get access to the user's name? Can we use the same approach?

**Comment by asadiqbal08** [comment]
@pdpinch I looked into both of these repo but did not find logic for the `user's full name` but they are also utilizing username there. Am I missing something ?

**Comment by pdpinch** [comment]
I don’t know how it works, but when I go to account.edx.org I can view and edit my name.

**Comment by asadiqbal08** [comment]
@pdpinch , The user's detail fetching structure in [frontend-app-profile](https://github.com/edx/frontend-app-profile) and [frontend-app-account](https://github.com/edx/frontend-app-account) is different with [frontend-component-header-edx](https://github.com/edx/frontend-component-header-edx). 
In the profile and account MFEs they are hitting the API endpoints to `edx-platform` to get these details via services, Please take a look on [example here](https://github.com/edx/frontend-app-profile/blob/master/src/profile/data/services.js#L23-L28)

While in `frontend-component-header-edx` MFE, They are relying on the details from another MFE `frontend-platform` [AppContext](https://github.com/edx/frontend-component-header-edx/blob/master/src/Header.jsx#L5) that I believe need to update in order to get user's full name in this MFE. 

Secondly, I believe there should be some configuration to check in order to show `user's full name` instead of `username` in  
[frontend-component-header-edx](https://github.com/edx/frontend-component-header-edx/blob/master/src/Header.jsx#L143) MFE. such as some variables in `.env`

**Comment by asadiqbal08** [comment]
Possible changes need to do in upstream edx MFE repositories. 

- Need to Update [frontend-platform block](https://github.com/edx/frontend-platform/blob/master/src/auth/AxiosJwtAuthService.js#L200-L216) something like this: 
```
async fetchAuthenticatedUser(options = {}) {
    const decodedAccessToken = await this.jwtTokenService.getJwtToken(options.forceRefresh || false);

    if (decodedAccessToken !== null) {
      this.setAuthenticatedUser({
        email: decodedAccessToken.email,
        userId: decodedAccessToken.user_id,
        username: decodedAccessToken.preferred_username,
        fullName: decodedAccessToken.name,
        roles: decodedAccessToken.roles || [],
        administrator: decodedAccessToken.administrator,
      });
    } else {
      this.setAuthenticatedUser(null);
    }

    return this.getAuthenticatedUser();
  }

```

2- Need to define the configuration inside `frontend-component-header-edx` MFE e.g. `config.SHOW_USER_FULLNAME `

3- Need to Update Header part [frontend-component-header-edx](https://github.com/edx/frontend-component-header-edx/blob/master/src/Header.jsx) with something like these changes: 

```
let userName = authenticatedUser === null ? null : authenticatedUser.username
  if (config.SHOW_USER_FULLNAME && authenticatedUser !== null) {
    userName = authenticatedUser.fullName
  }

```

This is just a dry code prototype, maybe some other changes required. @pdpinch if you are good then tomorrow I will go to create upstream PRs as suggested above.

**Comment by asadiqbal08** [comment]
As it is put on hold, can we close this or move from the board ?
