### ISSUE TITLE
Revamp Financial Assistance to use `ProgramRequirement`

### ISSUE THREAD

**Issue by asadali145** [mitodl/mitxonline#1464]
Our financial assistance flow currently uses the `Course.program` field. We want to move towards using `ProgramRequirement` and want to avoid data duplication. The current implementation of financial assistance only supports/assumes that a course will only be a part of a single program.

With `ProgramRequirement`, we can add a course to multiple programs and therefore need to update the financial assistance flow. A related discussion is under https://github.com/mitodl/mitxonline/issues/1220. Here is how we are going to handle financial assistance when a course is a part of multiple programs:

> Here's a concrete example:

> - Learner goes to about page for 14.100x. It's a member of program 1 (Development Economics) and program 2 (US Economics)
> - They click the link to request financial aid and fill out the form. Their country & income combination requires approval.
> - A team member of program 1 or program 2 approve it.
> - Now the learner gets the personal price for any course that is a member of program 1 or program 2.

#### Acceptance Criteria:

- [ ] Replace `Course.program` with `ProgramRequirement` in the Financial Assistance flow.
- [ ] Update the financial assistance form submission.
- [ ] Update the refine staff dashboard if needed.
- [ ] Update the pricing/checkout flow if needed.

#### Out of Scope

- Usages of `Course.program` outside the financial assistance flow.

**Comment by asadali145** [comment]
FYI @pdpinch @jkachel @rhysyngsun,
In case a course is added to multiple programs, Here is what our implementation will look like:

- Financial Assistance form link will be generated for any of the programs having financial assistance e.g. we have program 1 and program 2 and both have FA tiers configured, it will return a link to the FA form for one of them. Users can use the link to submit the form.
- The FA Form submission will also send a course run ID(not visible to the user)
- We will create a FA request for each program.
- Admin will be able to see multiple FA requests and approve them.

**Comment by asadali145** [comment]
FYI @pdpinch @jkachel,
There are still some uncertainties/questions around the implementation of this ticket.

- We do not have any information about the course when a financial assistance form is associated with a program.
  - Let's assume we have 2 courses `Course A` and `Course B`, `Both` are added as a requirement in `Program 1`. We also have `Program 2` with `Course A` as a requirement and `Program 3` with `Course B` as a requirement.
  - User visits the detail page of Course A and we display the link to the FA form for one of the programs, in this case, we display the link to the FA form of Program 1.
  - User submits the form for `Program 1`.
  - If we use the courses added in Program 1 and get a list of all courses then we could end up creating a request for all 3 programs.
- In case of multiple FA requests
  - How are we going to determine the auto-approval? Which request should be auto-approved?
  - Which submission should be considered when the requests are in differing states like reset, denied, etc?
  - Which previous submission should be used once the request is submitted? Requests can be pending approval, reset, or denied.
- How are we going to determine the FA tiers in case a course is associated with Multiple programs? Tiers are used for the auto-approval.

Currently, the FA form can be associated with a courseware object in 2 ways. This adds up to the complexity as well.

- CMS parent/child page relationship
- Course/Program dropdown fields in the FA CMS form.


Creating and managing multiple requests behind the scenes seems to be a complex implementation. On the other side, adding a view for the users to choose the programs while applying for the FA seems to be a fairly simple/manageable approach.

**Comment by jkachel** [comment]
My thoughts below. The big thought here is this: we _can't_ create financial assistance requests for multiple applicable courses/programs from a single submission. A decision has to be made.

The financial assistance forms are CMS pages, so the program admin* can make any modifications they wish (outside of the two standardized fields we require of all form submissions). This means they can change the text, but they can also adjust the form itself (this would be a bad idea, but they can do it), and, most importantly, they can do the income verification step differently. Income verification is done via DocuSign outside of the MITx Online system. Looking through the forms that are out there on production now, there's already a case where there are different DocuSign forms being used for this - DEDP has one, and we've also got FA turned on for 3.012Sx, and that has a different form in it. If the learner applies for a course using Program 1's form and we automatically create a request in Course X and Course X has different data requirements and a different income verification form, the learner will never be presented with that info, so the request for Course X is really invalid. Hence, we need the learner to decide which form is most applicable to their situation. 

> If we use the courses added in Program 1 and get a list of all courses then we could end up creating a request for all 3 programs.

see above - we'd end up with a FA just for the courseware object the learner requested.

> How are we going to determine the auto-approval? Which request should be auto-approved?

Each request auto-approves based on the tiers that it has. So, this entirely depends on which FA form the learner uses to submit the request. 

> Which submission should be considered when the requests are in differing states like reset, denied, etc?
> Which previous submission should be used once the request is submitted? Requests can be pending approval, reset, or denied.

If the request is denied or reset, we do two things:
* An appropriate action is taken when they go to the FA form for that particular courseware object. (So, if their request was denied for Program B, then they get a "sorry, no can do" message, but if it's reset for Course 1, they get the opportunity to reapply.)
* When we go to auto-apply the discount, these don't factor in because they're not approved. 

> How are we going to determine the FA tiers in case a course is associated with Multiple programs? Tiers are used for the auto-approval.

The FA form itself - we'd need the learner to make a choice about which they need to apply to. (My gut tells me this will generally just be programs and the learner will just choose the program they're most concerned about.)

There's another wrinkle here, I think. Regarding application of the FA discount: my suggestion is that we just always use the best one if there's multiple approved FA requests for the learner. So, in the case of the learner in Course A that has applied for FA in Programs 1 and 3, if Program 1 has their tier being a 65% discount and program 3 has their tier being a 25% discount, we'd choose the 65% one. I think this can potentially become fraught with peril, though - would there be a case where there'd be an issue with this? Like, if someone is registered for a course in both (to use really generic examples) a Science program and an Engineering program, where the Engineering one offers better financial assistance, does the Science department take issue with the fact that the learner got a better discount on the shared course? 



\* there's probably a real term for this but I'm just calling it program admin - it's whoever is in charge of approving these things and/or editing the course or program's info in the CMS.

**Comment by jkachel** [comment]
Resurrecting this since we're now going to have two programs on MITx Online which will share some courses, and that should also share financial assistance tiers. 

Thinking about this - the core of the system is `determine_courseware_flexible_price_discount`, which looks for the applicable courseware objects that the learner is trying to purchase. (In our case, this is always a course since we don't allow you to buy programs yet.) This uses a call to `get_ordered_eligible_coursewares` to determine this - if you pass it in a CourseRun it returns either the Course or the Program it belongs to. This needs to be updated anyway because it doesn't use `ProgramRequirements` and instead looks just at the `Program` FK. But, if it's looking in `ProgramRequirement`, we can then look for courses that belong to other `Programs`. In other words:
- If I'm purchasing a course that is standalone (doesn't belong to any programs via `ProgramRequiremetns`), it should work as it does and consider FA applications that pertain only to that course.
- If I'm purchasing a course that belongs to a single program, it should look for FA applications that apply to the course or to the program that it belongs to. It should _also_ look through the program to see if any courses that are in the program's `ProgramRequirements` tree also belong to a second program; it should then consider FA applications that apply to those programs as well.
- If I'm purchasing a course that belongs to multiple programs, automatically consider those but also do the related search.

There's some potential here for things to become messy if requirements end up looping back on themselves, but for this particular use case, I think that's a question for later. 

Another option would be to have an intermediate table that would allow us to group programs for financial assistance - if they're in the group, then any FA decisions apply to any of the programs in the group. Not sure how this works out given ProgramRequirements - if the course itself is in two programs, then we could consider them grouped by default but if it's not, then it's just the program that it's a requirement node for and then anything in the groups that the program belongs to. 

We also have the question of the financial assistance form itself. This has two prongs:
- The forms themselves should be very similar - they will be in this case anyway, I think?, but this is just to prevent confusion for the end user.
- The logic that checks for a financial assistance submission should also use the same method as we're using to determine tier application to figure out if there's been an existing approval or denial. If these exist, then those decisions apply across the board - I can't apply for DEDP Public Policy if I've already been denied in regular DEDP. 

I think that covers the bases. Thoughts (@pdpinch especially)? (Or should this move to a discussion post?)

**Comment by collinpreston** [comment]
Just curious, is there the possibility that a user is approved for different Financial Assistance requests that:
- Are associated with different courses, but all of those Courses are requirements of a single Program.
- Have different price reductions.
If so, would we take the highest level of Financial Assistance?

**Comment by jkachel** [comment]
> Are associated with different courses, but all of those Courses are requirements of a single Program.

Currently it will pull whatever financial assistance request that's available for the course or the program that it resides in. Looking at it, it'll need to change some - it just finds the first one that's current and approved and returns that, so it should be updated to collect them and then return the best one. 

> * Have different price reductions.
>       If so, would we take the highest level of Financial Assistance?

The discount code should always take the best discount. The financial assistance code just grabs the first one for now but it should follow this rule too.

**Comment by collinpreston** [comment]
The intermediate table solution sounds like to be robust and clearly defined.

**Comment by pdpinch** [comment]
Can this be closed?

**Comment by jkachel** [comment]
Yes, I believe we've basically accomplished this.
