### ISSUE TITLE
Username taken error not displayed during registration

### ISSUE THREAD

**Issue by collinpreston** [mitodl/mitxonline#1541]
### Steps to Reproduce

Start the registration process.  When asked to enter your username, enter a username that matches an existing user.

### Expected Behavior

Error message is displayed indicating that this username has already been taken.

### Actual Behavior

No error message is shown.

**Comment by pdpinch** [comment]
Is this different from the one you just fixed? On Apr 11, 2023, at 12:42 PM, Collin Preston ***@***.***> wrote:﻿
Steps to Reproduce
Start the registration process.  When asked to enter your username, enter a username that matches an existing user.
Expected Behavior
Error message is displayed indicating that this username has already been taken.
Actual Behavior
No error message is shown.

**Comment by collinpreston** [comment]
@pdpinch Very similar but just dealing with username, which I forgot had validation on the backend.
