### ISSUE TITLE
Dashboard and Program record are showing different things

### ISSUE THREAD

**Issue by annagav** [mitodl/mitxonline#1643]
### Steps to Reproduce

The dashboard of the user in ticket https://github.com/mitodl/hq/issues/1512 is showing nothing for the course 14.310 while they do have a certificate for it.  As a result the user cannot view the certificate.
The grade records are showing the course grade correctly.

<img width="574" alt="Screen Shot 2023-06-01 at 8 45 23 AM" src="https://github.com/mitodl/mitxonline/assets/7574259/c8ad4b05-ce4c-4a01-bb26-7e91e3e0799b">
<img width="1206" alt="Screen Shot 2023-06-01 at 8 45 42 AM" src="https://github.com/mitodl/mitxonline/assets/7574259/c32eda49-e505-4810-8fa8-2613f7d558c9">

**Comment by annagav** [comment]
I found another case (in Microeconomics course) with this bug https://github.com/mitodl/hq/issues/1549

**Comment by rachellougee** [comment]
Looked into the discrepancies between Dashboard and Program record

For [mitodl/hq/issues/1512](https://github.com/mitodl/hq/issues/1512), this user is currently enrolled in two runs  `course-v1:MITx+14.310x+2T2021` and `course-v1:MITxT+14.310x+1T2022` for course 14.310x, but there is only grade for 1T2022 (not 2T2021), this is how it looks like under My Course on the dashboard for this user, one is

![image](https://github.com/mitodl/mitxonline/assets/3138890/707ad037-4b7a-4a4b-8d75-9ad3c024180d)



For [mitodl/hq/issues/1549](https://github.com/mitodl/hq/issues/1549), this user is currently enrolled in `course-v1:MITxT+14.100x+2T2022`, but there is only passing grade for `course-v1:MITx+14.100x+1T2021`, so it's not displaying passed tag for course 14.310x because no passing grade for the enrolled run `course-v1:MITxT+14.100x+2T2022`

<img width="791" alt="image" src="https://github.com/mitodl/mitxonline/assets/3138890/21c63dd7-d176-4166-8e0f-8bb6b20294c0">

Their enrollments/grades are from MicroMasters, I don't know why sometimes users have grades (finalgrade) for runs they didn't enroll (dashboard_cachedenrollment) on MM. 
 
On the dashboard, each card is corresponding to that specific run (enrollment/grade needs to be matched for the run). On the program record, it's pulling the grade/certificate based on the course. I think this is why we see the difference between the two.

To fix this, there are two possible ways:
- Update their passing grade run to match their enrollment runs 
- Update the dashboard's `Course Passed` tag to be based on the course, not run. So in the first screenshot, both cards should be displaying `Course Passed`

@annagav @pdpinch Please let me know your thought on this

**Comment by annagav** [comment]
What if we have the "Course Passed" tag be based on a certificate, just like it is done in the Program Records, so then they are consistent.

**Comment by pdpinch** [comment]
- We should try manually creating a new enrollment to fix one of these cases, to see if it has the effect we think it will. 
- I'd like to see a list of all the cases of mismatched enrollments and grades, so I can get an idea of what the effect might be if we fix them all this way.

**Comment by rachellougee** [comment]
I manually added [course-v1:MITx+14.100x+1T2021](https://mitxonline.mit.edu/admin/courses/courserunenrollment/141886/change/) enrollment for the user reported in https://github.com/mitodl/hq/issues/1549 
This user's dashboard now displays a certificate for Microeconomic. 
- <img width="927" alt="Pasted Graphic 2" src="https://github.com/mitodl/mitxonline/assets/3138890/8d7389ce-314e-4f62-b21a-c7b02fac2312">

There is a bug on the dashboard that we need to fix for this user case https://github.com/mitodl/hq/issues/1512. When there are multiple enrollments for the same course, it doesn't always pick the one that has a Grade/Certificate.

@pdpinch Here is a list of course certificates that don't have enrollment  https://bi.odl.mit.edu/queries/1290. Since I manually add one, it's 98 now

**Comment by pdpinch** [comment]
Thanks for the list. I think we should go ahead and write a migration for this. I presume the new enrollments will eventually show up in the data platform. 

> There is a bug on the dashboard that we need to fix for this user case https://github.com/mitodl/hq/issues/1512. When there are multiple enrollments for the same course, it doesn't always pick the one that has a Grade/Certificate.

I don't think I understand this. Doesn't the dashboard display a card for each enrollment? In any case, you should open a new issue for this.

**Comment by rachellougee** [comment]
@pdpinch To be specific, it's on the program drawer, not the card under "My course". On the program drawer, there is logic to decide which enrollment to show for a course, it's not per enrollment. In this case, https://github.com/mitodl/hq/issues/1512, this user has two enrollments `course-v1:MITx+14.310x+2T2021` (no certificate) and `course-v1:MITxT+14.310x+1T2022` (with certificate), it picks the one without the certificate `course-v1:MITx+14.310x+2T2021`, see the screenshot in the ticket.

I will write a migration for the missing enrollment, I was planning to fix this bug as well since that's what this ticket is for. I will create a new issue if it's too much involved for this bug
