### ISSUE TITLE
Program certificate generation does not adhere to nested program electives

### ISSUE THREAD

**Issue by collinpreston** [mitodl/mitxonline#1691]
### Steps to Reproduce

Using a program which has electives like:
- Minimum of 2 course certificates from the following courses:
- Course1
    - Only one certificate is counted from the courses below:
    - Course2
    - Course3

Add course certificates for your user for Course2, Course3
### Expected Behavior

No program certificate should be generated since only one certificate from either Course2 or Course3 is counted towards the elective requirement.

### Actual Behavior

A program certificate is generated for your user.

**Comment by pdpinch** [comment]
How is this working now?Or is this a regression? On Jun 23, 2023, at 4:21 PM, Collin Preston ***@***.***> wrote:﻿
Steps to Reproduce
Using a program which has electives like:
Minimum of 3 course certificates from the following courses:
Course1
Course2
Course3
One certificate must be from:
Course4
Course5
Enroll your user into Course1, Course2, Course3.
Add course certificates for your user for Course1, Course2, Course3.
Expected Behavior
No program certificate should be generated since your user does not have a certificate for either Course4 or Course5.
Actual Behavior
A program certificate is generated for your user since there are 3 course certificates matching elective courses.
Good place to start
https://github.com/mitodl/mitxonline/blob/712d356c9e71227983541f7daef0d746c82fdaab/courses/api.py#L865

**Comment by collinpreston** [comment]
@pdpinch it doesn't appear to me that program certificates generating has ever considered the use case detailed in the issue.

**Comment by pdpinch** [comment]
Maybe I'm misunderstanding the issue. Here is the current configuration for DEDP:

![image](https://github.com/mitodl/mitxonline/assets/430126/12ad20e4-06f5-46a4-8f31-832817ca711b)

Are you saying this isn't functioning?

**Comment by collinpreston** [comment]
@pdpinch What I'm saying is that the certificate generation will ignore that "Requirement 3" under electives.

**Comment by pdpinch** [comment]
I'm not sure what you mean by

> certificate generation will ignore "Requirement 3" under electives and treat the courses associated with "Requirement 3" as merely elective courses. 

I'm not saying there isn't a bug, but I think you're misunderstanding how the DEDP program is meant to function. 

Here is how Nathan explained it: https://github.com/mitodl/hq/discussions/3

Here's a concrete summary:

Learners are not necessarily required to take at least one of Requirement #3. To meet the elective requirements they need to take 2 courses, but they can't take _both_ 14.73x _and_ 14.009x (because they are both "intro"). 

So these 5 combinations of electives are allowed:
14.740x and 14.750x
14.740x and 14.73x
14.740x and 14.009x
14.750x and 14.73x 
14.750x and 14.009x 

But this one is not:
14.009x and 14.73x 

Most importantly, are they any cases in production were we have mistakenly given a user a program certificate who didn't meet these requirements?

**Comment by collinpreston** [comment]
@pdpinch Oh wow, yeah that's not how I interpreted the nested "Minimum # of" branch in electives.  I still think this is a bug.  From the way it looks, the application is just counting any and all courses that are part of the electives towards the elective requirement, regardless of the nested branch.
