### ISSUE TITLE
Enroll button is still active after user has enrolled

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#184]
### Steps to Reproduce

1. Visit a course detail page, like https://rc.mitxonline.mit.edu/courses/course-v1:MITx+14.310x/
2. Enroll
3. Confirm the enrollment appears on the dashboard
4. Return to the course detail page

### Expected Behavior

- Enroll button should be deactivated. On xPRO this means that the text changes to "Enrolled" and the button has a white background with red text and red outline. 

### Actual Behavior

- Enroll button is still active.

**Comment by gsidebo** [comment]
@pdpinch The button just appears active because of the styling. The text changes to "Enrolled ✓" and the button becomes just a simple link to the edX course page. 

![ss 2021-09-13 at 16 59 22 ](https://user-images.githubusercontent.com/14932219/133162343-dbb59645-c0e7-4b73-a394-604bd86b6010.png)

Looks like there are two things to fix here:

1. Update the styling to the xpro-esque red outline you described
2. Remove the link to the edX course page if it hasn't started yet (we already made this fix in the dashboard, but we neglected this page)

**Comment by pdpinch** [comment]
> @pdpinch <https://github.com/pdpinch> The button just appears active because of the styling. The text changes to "Enrolled ✓" and the button becomes just a simple link to the edX course page.
> 

Wow. I totally missed that. 
> Update the styling to the xpro-esque red outline you described
That would be clearer. I think it would help also to remove the hover state. 
> Remove the link to the edX course page if it hasn't started yet (we already made this fix in the dashboard, but we neglected this page)
Yes.
