### ISSUE TITLE
Allow users to unenroll in courses from the dashboard, even after the enrollement end date has passed

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#312]
In #217 and PR #257 we added an unenroll option to the dashboard. Unfortunately, we later learned that the API we were using `/enrollment/` doesn't allow users to unenroll after the course's enrollment end date has passed. 

Clearly, this works on edx.org, so there must be another permission on the API, or separate API that allows this. 

#### Acceptance Criteria:

- [ ] research how this is achieved on edx.org. It appears they may use another end point, `change_enrollment` but the UX is multi-step
- [ ] make any necessary updates to edx-api-client
- [ ] update this app to use the new edx-api-client

#### Out of Scope

- When we start taking payments as part of #297, we will need to restrict unenrollment to audit enrollments.

**Comment by Wassaf-Shahzad** [comment]
@pdpinch @blarghmatey 
After looking into the code for enrollment api . I was able to determine the reason why a learner cannot unenroll after enrollment end date has passed. The main reason reason is that when we hit the api to unenroll and basic sanity checks  have passed  it tries to verify that the `HTTP_X_EDX_API_KEY` header matches with the `EDX_API_KEY` which in our case is not set in ol-infrastructure  and it switches the control flow to the next `else block` 

The reason we are getting a 400 is because the `else block`  tries to reactivate enrollment without verifying the original intent of the request and it throws an `EnrollmentClosedError` as essentially we are trying to enroll in a course which has closed its enrollments.

**Comment by pdpinch** [comment]
I don't understand. What do we need to do to fix this?

**Comment by Wassaf-Shahzad** [comment]
> EDX_API_KEY

We need to to set the EDX_API_KEY environment variable and OPEN_EDX_API_KEY environment variables  in  
ol-infrastructure Hopefully

**Comment by pdpinch** [comment]
See https://github.com/mitodl/ol-infrastructure/pull/515

**Comment by Wassaf-Shahzad** [comment]
@pdpinch I have verified this on my end and Its seems to be working know (after we added the  EDX_API key).

**Comment by pdpinch** [comment]
Ok, now that the API is working, I have two more questions:

- Are there any code changes we need to make to allow users to unenroll in the UI? Or can they do it now?
- In the PR mitodl/ol-infrastructure#515 it says that the API key setting we are relying on is deprecated. Can you confirm that? If that is true, what do we need to do to stop relying on `EDX_API_KEY`?

**Comment by Wassaf-Shahzad** [comment]
> Ok, now that the API is working, I have two more questions:
> 
> * Are there any code changes we need to make to allow users to unenroll in the UI? Or can they do it now?
> * In the PR [Adding values for edx_api_key to address enrollment bug in xPro ol-infrastructure#515](https://github.com/mitodl/ol-infrastructure/pull/515) it says that the API key setting we are relying on is deprecated. Can you confirm that? If that is true, what do we need to do to stop relying on `EDX_API_KEY`?

- On the UI side we dont need any changes. The unenroll is working (i verified it, if someone else can take a look that would be great too)
- I would need to do some more RnD but with the current api that we are hitting it is highly unlikely that we could get rid of 'EDX_API_KEY'

**Comment by pdpinch** [comment]
I think we still have some (frontend?) code that is blocking users from unenrolling after the `enrollment_end` is past. 

For example, on RC I get this pop-up when I try to unenroll from [course-v1:MITx+JPAL102x+3T2021](https://rc.mitxonline.mit.edu/admin/courses/courserun/5) 

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/430126/151669106-3b95493e-31c9-432d-897f-2d6f8184a6b4.png">

**Comment by Wassaf-Shahzad** [comment]
> I think we still have some (frontend?) code that is blocking users from unenrolling after the `enrollment_end` is past.
> 
> For example, on RC I get this pop-up when I try to unenroll from [course-v1:MITx+JPAL102x+3T2021](https://rc.mitxonline.mit.edu/admin/courses/courserun/5)
> 
> <img alt="image" width="1154" src="https://user-images.githubusercontent.com/430126/151669106-3b95493e-31c9-432d-897f-2d6f8184a6b4.png">

@pdpinch  I did some RnD and I dont know why the `EDX_API_KEY` is being considered depreciated as it is clearly still being used  here https://github.com/openedx/edx-platform/blob/db32ff2cdf678fa8edd12c9da76a76eef0478614/openedx/core/lib/api/permissions.py#L35

Regarding your inquiry for the frontend code stopping users from unenrolling, That  is due to course runs enrollment end date and is not related to edx-platform side this is a small check. For the current issue to even be raised the user should be able to press `Unenroll`  ie
 
 - The course runs enrollmend end date in MITxOnline  >  Courses enrolment end data in edx-platform

We can can remove the check if we want.

**Comment by briangrossman** [comment]
> Regarding your inquiry for the frontend code stopping users from unenrolling, That is due to course runs enrollment end date and is not related to edx-platform side this is a small check. For the current issue to even be raised the user should be able to press `Unenroll` ie
> 
> * The course runs enrollmend end date in MITxOnline  >  Courses enrolment end data in edx-platform
> 
> We can can remove the check if we want.

This above will be addressed by: https://github.com/mitodl/mitxonline/issues/403

Closing this issue.
