### ISSUE TITLE
open edx: breadcrumb trail links give page not found errors (non-staff users)

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#345]
### Steps to Reproduce

- Go to a course as a non-staff user
- Navigate to course content
- Click on a link in the breadcrumb trail, including the course home link

### Expected Behavior

- You will be taken to the appropriate pages in the course

### Actual Behavior

- You receive a `Page not found` error
- It appears as though the `/learn` folder preceding the `/course` folders is missing. E.g.
   - [correct link](https://courses.mitxonline.mit.edu/learn/course/course-v1:MITxT+21A.819.1x+3T2021/block-v1:MITxT+21A.819.1x+3T2021+type@sequential+block@19992ce942e34ae1a6ef35d0de9d3504/block-v1:MITxT+21A.819.1x+3T2021+type@vertical+block@63f2b14d41e84c06a09413bfb012b764)
   - [incorrect link](https://courses.mitxonline.mit.edu/course/course-v1:MITxT+21A.819.1x+3T2021/block-v1:MITxT+21A.819.1x+3T2021+type@sequential+block@19992ce942e34ae1a6ef35d0de9d3504/block-v1:MITxT+21A.819.1x+3T2021+type@vertical+block@63f2b14d41e84c06a09413bfb012b764)

### Screenshot or Screencast

**Breadcrumb Trail**
<img width="1171" alt="Screen Shot 2021-12-20 at 10 20 11 PM" src="https://user-images.githubusercontent.com/21342568/146865481-0363918a-9b37-4696-87d6-583d542f3fbf.png">

**Page not found**
![image](https://user-images.githubusercontent.com/21342568/146865537-136519f7-916c-417d-b395-0ad543d7e5b6.png)

**Comment by arslanashraf7** [comment]
@briangrossman , Looks like this is probably related to the branch we're running for MITxOnline(Which in MITxOnline's case is `master`).

I recently created a PR to fix this breadcrumbs issue but that's merged into `open-release/maple.master` (https://github.com/edx/frontend-app-learning/pull/780) so in any MFE instance where we are running `maple` should be working fine.

**Proposed Fix:** We need to get the original PR(https://github.com/edx/frontend-app-learning/pull/777) merged into the master and this issue should be resolved.

Based on the above, @blarghmatey Can you confirm the `Learning MFE` branch we are running in `MITxOnline`?


@pdpinch, FYI, we should also need to merge https://github.com/edx/frontend-app-learning/pull/777 into master since its backport(https://github.com/edx/frontend-app-learning/pull/780) has already been merged into `maple`.

**Comment by blarghmatey** [comment]
For MITx Online we are building off of the master branch of the learning MFE

**Comment by pdpinch** [comment]
Arslan’s fix for this was merged into the learning MFE yesterday 

https://github.com/edx/frontend-app-learning/commit/de49e8b2717023f12a29a08dda77bd4a66c5bb69

**Comment by briangrossman** [comment]
@arslanashraf7 - Nice work on this.

@blarghmatey put this into production today. Closing this issue... but... like a phoenix... https://github.com/mitodl/mitxonline/issues/347 has risen from it's ashes... 

There are still some issues with this MFe
