### ISSUE TITLE
Accessibility: Bypass Blocks: Implement a mechanism to bypass the header on site pages

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#419]
As a user navigating the site with a screenreader, I want a way to be able to bypass the header on all pages so I don't need to listen to it on every page. 

#### Designs and Mockups and Specifications

Ideally, users would be able to bypass the header to get directly to the main content on the page
<img width="433" alt="image" src="https://user-images.githubusercontent.com/21342568/154622920-3d8ed59d-91ba-4d5f-9e1d-6a7b8434fc76.png">

From our testers:
> A bypass is a mechanism is present to bypass blocks of content.
> 
> Here are the options of how to solve this:
> https://www.w3.org/WAI/WCAG21/quickref/#bypass-blocks
> 
> On this page, since you already implement other ARIA landmarks (nav, footer); it might be easiest to add a MAIN landmark.

#### Acceptance Criteria:

- [ ] Implement a mechanism as specified here: https://www.w3.org/WAI/WCAG21/quickref/#bypass-blocks to enable users to bypass the header on every page

Note that all pages except the home page have a section called `main-page-content` where the main page content begins.

**Comment by umarmughal824** [comment]
Here is my finding there a few ways like
Let suppose we have a main element with id like 

```
<div id="main">
...............
</div>
```

There are the following ways

- Append the id of the main content in the link like <page_url>#main 
   It means on every page load it will automatically append the `#main` in the link of each page so it will skip the header section and directly scroll to the main content of the page

- [G1: Adding a link at the top of each page that goes directly to the main content area](https://www.w3.org/WAI/WCAG21/Techniques/general/G1.html)
  It's like let's suppose we have a website containing an e-commerce store having a lot of categories so we don't want the screen reader to go through each of it. But at the top of the page, we will be providing a link with `Skip to main content` that will directly skip the header and will bring the scroll and focus to the main content section. So on every page load, the screen reader will go to that link so that users could skip it

- [G123: Adding a link at the beginning of a block of repeated content to go to the end of the block](https://www.w3.org/WAI/WCAG21/Techniques/general/G123.html)
   It's like defining a link against each section of the page so that the user could directly skip to that specific section of the page in our case if the user is on course/program. he wants to directly point to the Staff team

- [G124: Adding links at the top of the page to each area of the content](https://www.w3.org/WAI/WCAG21/Techniques/general/G124.html)
  So after adding the links of each section of the page we could define a menu at the top of each page where we could have the skip links to each section

- [CR28: Using an expandable and collapsible menu to bypass block of content](https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR28.html)
   So we could the Skip menu that would be expandable or collapsible menu containing all the skip links to skip to that specific part of the page

- [H69: Providing heading elements at the beginning of each section of content](https://www.w3.org/WAI/WCAG21/Techniques/html/H69.html)
   If we have a repeated section so better to define a header that would be indicating start of the each section

We have an open source plugin as well that follows these rules. That is the plugin link https://paypal.github.io/skipto/ and here how it shows the menu 

![image](https://user-images.githubusercontent.com/4043989/156778869-98073eca-125f-4dbd-9268-89ea63b3c06f.png)

**Comment by umarmughal824** [comment]
@briangrossman what's your opinion on my findings, what is the suggested way?

**Comment by briangrossman** [comment]
@umarmughal824 Thank you for taking the time to interpret all these approaches and provide descriptions. 

In this case, the option [G1: Adding a link at the top of each page that goes directly to the main content area](https://www.w3.org/WAI/WCAG21/Techniques/general/G1.html) is what we're looking for. 

A few additional notes:
- Users won't automatically skip the header, but users can opt to skip it by clicking on the link you create
- This link shouldn't be visible on screen, but will be read by screen readers and is focusable and accessible via tabbing
