### ISSUE TITLE
Ecommerce: when checkout completes, delete only the basket that was checked out

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#453]
Currently when a user checks out their basket, we defer deletion of the basket under later - this could be a) when the browser navigates back to the site or b) when the payment processor sends us an API request. Right now we just delete whichever basket the user has, but that may be a _new_ basket, particularly if the API call is deferred, and we don't want to inadvertently stomp on that state.

I'd propose that we adjust the callback and api urls to accept a basket id as part of the url path. Then we selectively `Basket.objects.filter(user=order.purchaser, id=basket_id)` and delete that one. Note that we want to filter both on the basket id and user.

**Comment by jkachel** [comment]
This is complicated somewhat by the fact that the Basket model has a one-to-one relationship with User, so there's a constraint there that means the user's only ever going to have one Basket. I think the only way you'd really be able to step on the state like that is in one of two places:
- You get an out-of-band call from CyberSource due to a deferred transaction (i.e. it lands in the Review limbo state and someone has to hit a button in the CS console). In this case, it can check for this (either by looking at the order status or by maybe even using the Transaction table once it gets the type field in #467) and then just not delete the basket at all. There wouldn't be a valid one anyway and there wouldn't necessarily be an active user at that point either, so just leave the basket alone. (This is probably the thing to do in this case anyway.) 
- Someone goes through the checkout process, then goes back through to the app and enrolls in another course while they're still in CyberSource. In this case, they'd have a new basket so when they finish up the CyberSource part of it, the new course they'd added to the cart would be removed (or, they cancel or their card is declined or something and they get punted back to the cart with something totally different in their cart). I tested this on RC successfully - enrolled in one course, hit Place Order, then opened a new window back to RC and enrolled in something different, then cancelled in CyberSource, and got back a cart with only the 2nd thing in it. In this instance, it might be better to clear out the basket before sending to CyberSource and then, if the user gets redirected back, reconstruct the basket they had so they're not missing an enrollment they thought they were getting. (The UI should handle multiple cart items even though we don't necessarily give users a way to do that.) 

Alternatively, I can redefine the relationship between Basket and User so it's not 1-to-1, and then put in some logic/flags to enforce one live basket per user/etc. Thoughts on this?

**Comment by jkachel** [comment]
Figured out how to do this - PR open for this now. The PR implements the out-of-band stuff and then adds in the check to not clear the cart if the payment is successful but the cart is now somehow different (ostensibly the "I started over on MITx Online while still checking out elsewhere" flow).
