### ISSUE TITLE
Ecommerce: open edX: Purchase a verified certificate option doesn't work from within a course

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#510]
### Steps to Reproduce

- Enroll in a course, but don't pay for it
- Go to the course in edX (see image below)

### Expected Behavior

- Either:
   -  there will not be a `Pursue a verified certificate` section on the page
   - the `Upgrade for $xxx` button will direct the learner through the ecommerce flow to update the course

### Actual Behavior

- Clicking on the `Upgrade for $xxx` button redirects the learner to their dashboard without purchasing

### Screenshot or Screencast

![Screen Shot 2022-04-11 at 9 47 54 AM](https://user-images.githubusercontent.com/21342568/162755806-2dfeb7f4-e8e7-4365-abfb-3eecc9ed336c.png)

**Comment by pdpinch** [comment]
I think this requires the plugin Arslan wrote https://github.com/mitodl/open-edx-plugins/pull/31

Has that been deployed to production?

**Comment by briangrossman** [comment]
Note that the `verified certificate` link in this section is broken as well.

**Comment by pdpinch** [comment]
This should be fixed by #556 and #610.

**Comment by arslanashraf7** [comment]
Posting an update on a few things that are testable on RC as of now:

- Course `Upgrade` button is only visible for the courses that have `Verified` course mode(In our case) added & the user is enrolled in a free mode e.g. `Audit`
- As of now, the plugin for redirecting the user to MITxOnline so clicking the `Upgrade` button will take the user to the cart in MITxOnline where the user can pay.
- After successful completion of payment from MITxOnline, if you visit this course in edX again you won't see any Upgrade button because the user is not enrolled in `Verified` Mode.

Summing up:

>Clicking on the Upgrade for $xxx button redirects the learner to their dashboard without purchasing

This is now working on RC

>Note that the verified certificate link in this section is broken as well.

As per https://github.com/mitodl/frontend-app-learning/pull/3 (This still needs a deployment though)

There would be no `verified certificate` link with the updated design 
Also, there should be no price mentioned with `Upgrade` button in the updated design


**What I enabled for testing purposes:**

By default the enrollments are not visible in Django Admin so, I added a waffle switch(`student.courseenrollment_admin`) to look through the `Enrollments` [here](https://courses-qa.mitxonline.mit.edu/admin/waffle/switch/4/change/). This will help verify that once the user purchases the course through MITxOnline, he gets enrolled from `Audit` to `Verified` course mode.

FYI, @briangrossman

**Comment by pdpinch** [comment]
@arslanashraf7 do you think we can close this?

**Comment by arslanashraf7** [comment]
@pdpinch Yes, We can close this through https://github.com/mitodl/frontend-app-learning/pull/3, https://github.com/mitodl/ol-infrastructure/pull/903, and https://github.com/mitodl/open-edx-plugins/pull/31. Though we need to remember to set the required infra-related settings when we ship there. Or if there is a checklist I can add it there as a reminder.
