### ISSUE TITLE
Courses display incorrect date on the dashboard

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline#523]
### Steps to Reproduce

- Go to your dashboard on MITx Online
- Look at the start dates listed for your courses
- Compare them to the actual start dates of the courses runs you're enrolled in
   - Here's a video of the issue

https://user-images.githubusercontent.com/21342568/164081620-ea60611e-9cea-456d-a676-11caae0dbc39.mov

### Expected Behavior

- The start dates listed in the dashboard should be the right dates for the runs you're enrolled in

### Actual Behavior

- The start dates are frequently wrong and appear to display a later date in some cases (possibly the latest date of the course you're enrolled in?)
   - This happens when you're enrolled in two runs of the same course (both that start in the past)
   - Both have the start date of the later run

### Stacktrace

- Here's a start for where to look: https://github.com/mitodl/mitxonline/blob/180b9f921b09882820a1ef008d27e09be28a620d/frontend/public/src/containers/pages/DashboardPage.js#L236-L321

**Comment by umarmughal824** [comment]
@briangrossman it seems to be working fine on my local machine. Here are the attached screenshots for the reference

<img width="1440" alt="Screenshot 2022-04-21 at 17 44 05" src="https://user-images.githubusercontent.com/4043989/164461076-a22b04d3-2aa1-4e03-b35d-e21b829276a2.png">
<img width="1439" alt="Screenshot 2022-04-21 at 17 45 51" src="https://user-images.githubusercontent.com/4043989/164461108-72fdd76e-fe50-49d2-a055-a20f84c98bc6.png">


Anyway, I will further troubleshoot it.

**Comment by briangrossman** [comment]
I tested a little more and a test case that seems to cause the bug is:
- you are enrolled in two runs of the same course
- both of the runs are in the past or both of the runs are in the future

If one of the runs is in the past and one is in the future, it displays correctly. Here's a video showing this.


https://user-images.githubusercontent.com/21342568/164466319-cbf502d5-b452-441e-8070-b58d65caf99f.mov

**Comment by umarmughal824** [comment]
@briangrossman even past or future course runs are still not repoducible. That's really weird

<img width="1440" alt="Screenshot 2022-04-22 at 17 28 01" src="https://user-images.githubusercontent.com/4043989/164719683-dcb0dc7b-9525-43f9-a416-cea76d423c57.png">
<img width="1438" alt="Screenshot 2022-04-22 at 17 29 05" src="https://user-images.githubusercontent.com/4043989/164719691-6ef6bc34-e467-4195-a232-5e3ee60fe05f.png">
<img width="1440" alt="Screenshot 2022-04-22 at 17 03 09" src="https://user-images.githubusercontent.com/4043989/164719660-841e9e03-4da7-496f-828c-9bc629da20ae.png">

**Comment by briangrossman** [comment]
Thanks, @umarmughal824  This one looks a little tricky. 

I chatted with @rhysyngsun a little about this today. We weren't able to identify the specifics of the problem, but here's a few thoughts:
- From Nathan: ```the only thing I can think of to try is moving renderEnrolledItemCard out of the react class and into its own functional component - I'm wondering if the binding of that function is causing issues with the variables```
- Also, when you look at (recent updates)[https://github.com/mitodl/mitxonline/blame/main/frontend/public/src/containers/pages/DashboardPage.js], there were a few updates made in `renderEnrolledItemCard` with this PR: https://github.com/mitodl/mitxonline/pull/404. That might be a good place to look. 

Good luck!

**Comment by jkachel** [comment]
FYI, asked devops(Tobias) about caching - there's Fastly in front of both RC and prod instances, so there is a cache there. I asked for the cache in Fastly to be cleared and that had no effect. Locally, the widgets have the dates correct (tested in `main`, `release-candidate`, and `release` branches just to be sure), even with test data from RC. So, not sure what the problem here is - maybe it's not building properly in Heroku? Will try doing a production build locally and diffing the JS bundles it generates against what's being served.

**Comment by jkachel** [comment]
Verified that caching and builds aren't the problem - checked by wading through the minified source on RC and the formatted date string (for some reason) there is persisting where it shouldn't be. As it turns out, this code is duplicated in the cart page (and this problem exists there too, except that you can't add >1 cart item via the frontend) so have now refactored that out too into a separate function, which should ensure all the variables it uses are scoped correctly.

**Comment by briangrossman** [comment]
@jkachel Wow. That sounds subtle. Thanks for digging in. 
🤞
