### ISSUE TITLE
Receipt: additional information and formatting 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#531]
As a user, I'd like to have enough information on the receipt so that I can share it with an employer for reimbursement. 

#### Designs and Mockups

as close as possible to this (from xPRO):

![image](https://user-images.githubusercontent.com/430126/164749837-0950ab39-1fca-4844-9387-32e550ead4c9.png)

#### Acceptance Criteria:

- [ ] include purchase date
- [ ] include learner name and purchaser name (these can be different)
- [ ] include address
        - I don't think we capture learner's address, but we should get the purchaser's address from Cybersource 
- [ ] include MITx Online logo
- [ ] include MITx Online address

**Comment by pdpinch** [comment]
This is on hold until @rhysyngsun can provide some guidance on how we can make this a library in ol-django

**Comment by rhysyngsun** [comment]
@pdpinch this is done in the react part of the application so I don't think it's within the scope of `ol-django`

**Comment by asadiqbal08** [comment]
@pdpinch I know, you added the screenshot from MitxPro as reference here. I looked around the current implementation of receipt page in MitxOnline and found these two screens that show receipt details. 


<img width="1676" alt="Screenshot 2022-05-16 at 5 08 13 PM" src="https://user-images.githubusercontent.com/7334669/168589585-e381988c-c159-495e-b00d-6e5714e5b638.png">
<img width="1665" alt="Screenshot 2022-05-16 at 5 08 05 PM" src="https://user-images.githubusercontent.com/7334669/168589611-9b7118cd-3a7c-437c-a97a-afa648e9b62d.png">

1- Let me know, where do you want to show some more details from the above screens. 
2- We have `purchaser` details e.g. name, email etc referring this [field](https://github.com/mitodl/mitxonline/blob/main/ecommerce/models.py#L246).
3- But, we do not have any receipt model in MitxOnline as we are dealing in MitxPro in order to get `card_type`, `card_number` or `purchaser name` etc from [data field](https://github.com/mitodl/mitxpro/blob/master/ecommerce/models.py#L650-L657) there.

Can you put more thoughts over it ?

**Comment by annagav** [comment]
Hi @asadiqbal08 I am sorry I forgot to assign this issue to me, because there was a change of intention with this issue https://github.com/mitodl/ol-npm-libraries/issues/18, and I was out few days last week. Did you already start working on this?

**Comment by annagav** [comment]
I think this issue was on hold because of this https://github.com/mitodl/ol-npm-libraries/issues/18. But we decided not to implement it yet. So I am removing the hold tag

**Comment by rhysyngsun** [comment]
@asadiqbal08 you can use this
![mitx-online-receipt](https://user-images.githubusercontent.com/28598/168624574-6fefdd16-6b57-4125-9934-bd1b9ea1b1f7.png)
