### ISSUE TITLE
Flexible Pricing: should be applied automatically when a course is added to the cart

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#541]
#### Blocked By
- https://github.com/mitodl/mitxonline/issues/573
- https://github.com/mitodl/mitxonline/issues/542

#### Summary

As a learner I want my financial aid applied automatically.

#### Designs and Mockups

I'm not sure we implemented this yet and it will probably be part of the financial aid dashboard work, but we need to ensure that when a learner goes to the checkout page they get it automatically applied since they will not have a discount code for it.

#### Acceptance Criteria:

- [ ] When a learner has been given financial aid and starts to purchase a course, their financial aid discount should be automatically applied on the checkout page.

**Comment by jkachel** [comment]
As a small note, MITxOnline already has a mechanism for automatically applying discount codes to a user's basket through the UserDiscount table. If the learner has a discount code assigned through that, the discount will be automatically applied, though it can be overridden. (Currently, the code doesn't account for discount amounts so learners could potentially override the user discount with a code of lesser value. It also doesn't factor value in when it auto-applies the discounts in the case that there's >1 user discount.)

**Comment by umarmughal824** [comment]
> discounts

Still that would require some work to be done here.

**Comment by umarmughal824** [comment]
#553 and #542 are the pre-requisites of that ticket. As once we will have the approved user financial aid data, only then it could be started to work on/

**Comment by umarmughal824** [comment]
@pdpinch / @rhysyngsun Tiers and TierPrograms are not defined yet so I am not sure how much discount to offer and on which criteria. So a brief introduction about that would be required to proceed.

**Comment by jkachel** [comment]
In terms of the discount criteria, this is what I understand the process to be: 

1. When the learner is directed to the checkout page, applicable discounts are applied to the Basket via `ecommerce.api.apply_user_discounts` if there aren't any discounts applied already.
   * Right now, this applies any UserDiscounts to the learner's Basket sequentially. 
   * The code here should be amended to apply any FlexiblePricing discounts. Per #542, there will be a FK from FlexiblePricing to Discount, so it should look for any discounts that apply to the Basket's contents. 
   * The code that auto-applies UserDiscounts should happen after this and it should also skip any UserDiscounts that aren't as valuable as the FlexiblePricing Discount. 
2. If the user applies a discount through the checkout UI, it needs to be skipped if it's less valuable than any existing discount applied to the Basket.
   * Right now, it just clears the existing discount and applies the specified one, regardless of whether it's better or not. 
   * By this point, any automatic discount should already be attached to the current Basket. Learners can't clear their Baskets at this point other than by adding a new item to the Basket (clicking Enroll on something clears your Basket). This is probably a place where the code should also clear out any discounts (or do something else to check the applied discounts) that have been applied so that the auto-apply code runs again.

**Comment by rhysyngsun** [comment]
@jkachel thanks for digging into that, good things to have on our radar - I think we should circle back on this after we've got the flexible pricing fully implemented since I'm sure there will be a few other edge cases / UX rough edges to clean up.

**Comment by umarmughal824** [comment]
Created an issue https://github.com/mitodl/mitxonline/issues/541
