### ISSUE TITLE
Ecommerce: add mangement command to load country income threshold data

### ISSUE THREAD

**Issue by umarmughal824** [mitodl/mitxonline#559]
#### Acceptance Criteria:
- [x] Management command to load country threshold data
- [x] Add this management command to `bin/post_compile` so it automatically updates on deployments

**Comment by umarmughal824** [comment]
@pdpinch I have a few questions about financial aid. 

- Are these income thresholds in USD or in local currencies?
- I have seen the file received from micrometers data marking 75000 as the income threshold for all of the countries

I did not find any other usage of defining different thresholds for each country so that means all these thresholds are manually updated against each country. So, in my opinion, we should define those in our data file rather than insert them manually which would save a lot of human effort. 

I am talking about that file https://github.com/mitodl/mitxonline/blob/bf8460d33ae0a05dd0cb48e3a6710e4884090d35/flexiblepricing/fixtures/country_income_threshold_data.json

So let me know what's your opinion?

**Comment by pdpinch** [comment]
> Are these income thresholds in USD or in local currencies?

USD

> I have seen the file received from micromasters data marking 75000 as the income threshold for all of the countries

If you look at the data on RC or in production, you'll see that it's different. We chose not to include this data in the open source repository.

**Comment by rhysyngsun** [comment]
@umarmughal824 I updated this ticket to just address the income threshold issue. I think this should be a management command that runs on every deploy - that way we can make updates to this data and it's just applied automatically. @pdpinch does this make sense? I'm guessing we don't change this too often and even when we do it's preferable to keep all our environments in sync.

I also added a separate issue (https://github.com/mitodl/mitxonline/issues/565) for adding this to django-admin, but I'm thinking we may not want to do that or at least make it readonly, because it will get overwritten if we do the above.

**Comment by pdpinch** [comment]
I don't think I have enough context to answer your question @rhysyngsun but I don't think this data has been updated in the database since 2018, when we added a threshhold for Argentia (AR) which had somehow been overlooked. 

FWIW, I also found the original data in the git history, e.g. https://github.com/mitodl/micromasters/blob/387a8ffe6bd837f0529684ca6409599f9e63caae/financialaid/data/country_income_thresholds.csv

**Comment by rhysyngsun** [comment]
@pdpinch I was thinking that if `country_income_thresholds.csv` was the canonical source of this data, that we'd just want it in a management command as opposed to a having to create a migration every time it changes - it's a change in data not schema.
