### ISSUE TITLE
Ecommerce: don't allow user to pay for the same course run twice 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#676]
### Steps to Reproduce

I haven't been able to reproduce this with my own user, but you can see it on RC if you masquerade as the user `ddoyle`. 

They also three receipts for the same course run

Receipt 1: https://rc.mitxonline.mit.edu/orders/receipt/172/
Receipt 2: https://rc.mitxonline.mit.edu/orders/receipt/285/
Receipt 3: https://rc.mitxonline.mit.edu/orders/receipt/292/

### Expected Behavior

- user should not be able to pay for the same course run twice. Perhaps there is an edge case where a user gets a refund and then wants to pay again, but that would require customer service intervention. 
- Normally we shouldn't even be displaying buttons to allow the user to pay for the same course twice. But we should also prevent this from having in the checkout page, in case the user somehow circumvents the UI (for example, by using a direct URL). 

### Actual Behavior

- Somehow this user paid for the same course run 3 times.

**Comment by rhysyngsun** [comment]
@pdpinch what are you thinking in terms of a refund and a customer service intervention? To fix this we'll need to filter out orders in certain states (e.g. pending, canceled, failures). The safest way to go about this is to filter to the statuses we want to include when determining if a course run is paid for.

**Comment by pdpinch** [comment]
This user is in a bad state: they have paid and don't have anything to show for it. They need to be either:
1. refunded and unenrolled in mitxonline
2. manually enrolled as verified in open edX. 

> To fix this we'll need to filter out orders in certain states (e.g. pending, canceled, failures). The safest way to go about this is to filter to the statuses we want to include when determining if a course run is paid for.

I don't understand what you mean by this☝️. All 3 orders are "fulfilled"

**Comment by rhysyngsun** [comment]
@pdpinch sorry, i think there's a couple of things here that I might've been muddling together:

##### The specific user issue on RC
This is currently a data issue I think, so repairing that isn't necessarily a thing we can do with a code change. If you want to fix the data I'd suggest:
- Fix the state to have the learner verified:
  - The enrollment dates need to be changed to a future date (if we can't do this, the other option is required)
  - Mark all but one order as refunded
  - Update the learner's `CourseRunEnrollment` record setting `edx_enrolled=False` and `enrollment_mode="verifed" (this will instruct MITx Online to set the enrollment to the correct mode in openedx)
- Update the learner's state to reflect their current `audit` 
  - Change all currently fulfilled orders to a `REFUNDED` state
  - Ensure the `CourseRunEnrollment` record is set to `edx_enrolled=True` to ensure no further syncs are attempted


##### Preventing this in the future
  - Ideally replace the current `sync_courseruns_data` with a webhook driven mechanism for immediate syncing of course run updates so we avoid or at least significantly reduce the likelihood of this.
  - From an organizational practices perspective, we should probably ask course authors that when they update enrollments dates if they are moving them forward in time that they provide a buffer (i.e. don't set it to "now"). Even with a webhook in place there's still a chance that there are in-flight orders (e.g. a user is on Cybersource paying). At least an hour to be safe would probably be good.
  - I'd suggest that we only allow a learner to purchase a run if they have **no** orders for that run in a `FULFILLED` or `REVIEW` state (I don't think we really use the latter, but I just want to make sure our bases are covered). I'm not sure about the `PENDING` state, mainly because I'm not certain off the top of my head if CyberSource guarantees that if the learner abandons checkout that the order exits that state and we get a webhook event to reflect that.
  - This means orders that a learner can be refunded and then later repurchase without support's help (I think we want to do this?)

**Comment by pdpinch** [comment]
thanks for the detail. 

When I wrote this, this is exactly what I had in mind: 

> we only allow a learner to purchase a run if they have no orders for that run in a FULFILLED or REVIEW state
