### ISSUE TITLE
Course Certificates: Poll open edX for updated grades

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#717]
As a user, I'd like to have a certificate generated within 24-48 hours of my having passed the course. 

- This is a simpler alternative to https://github.com/mitodl/mitxonline/issues/690

#### Acceptance Criteria:

- [ ] Update learners' grades (in open courses) on mitxonline, from open edX, on a regular basis
- [ ] If the learner has passed a course, generate a certificate for them
- [ ] some courses won't want certificates generated until proctored exam results have been reviewed

#### out of scope

- alert learners by email when a certificate has been generated for them

**Comment by pdpinch** [comment]
Virtual proctored exam grades will be included in the overall course grade, so one query per course should be sufficient.

**Comment by pdpinch** [comment]
I can’t think of any reason to change the enrollment status when the certificate is generated. Nothing else at this time. 

> Once we know the learner has passed the course and we generate the certificate for them, is there anything else specific w.r.t to MITxOnline that we might want to do? e.g. Any changes in enrollment etc?

**Comment by arslanashraf7** [comment]
Update:

So, I've ported most of the things from MITxPRO and wanted to take input before the PR is actually finalized. So the current workflow is like this:

1. We will have a cron job/scheduled celery task for certificates generation that by default runs daily at midnight just like xPRO (We have settings through we can customize it if we'd like [reference](https://github.com/mitodl/mitxonline/pull/722/files#diff-96677aa35debfefd031d9d34d9c70369754ee3acb2d9a9d4090e98612efee6f5R86-R93) ).

2. While generating certificates, the task will consider all the course runs whose end date has passed and their certificates haven't been generated yet. (We also have a delay setting in xPRO which will allow us to generate the certificates with a delay when the end date has passed [reference](https://github.com/mitodl/mitxonline/pull/722/files#diff-96677aa35debfefd031d9d34d9c70369754ee3acb2d9a9d4090e98612efee6f5R62-R65))

3. Certificates will be generated for all the users that have passed the course

**Things that are still in progress:**
>some courses won't want certificates generated until proctored exam results have been reviewed

Currently, I'm trying to set the proctored exams in edX to check if the grades API respects the status of the Proctored Exam e.g:
1. If the overall grades are above passing percentage, does that grades API respect if the `Proctored Eams` were reviewed or not? This means if a user has passing grades in a course but his proctored exam hasn't been. reviewed, does the send `passed=False` (If Yes, we might not need to change anything )
2. If the grades API doesn't respect the Proctored Exam status, we will need to see how we will handle this case.

**Question:**
Since we also working through programs, Are we currently looking into creating Program Certificates too? If yes, What would be the list of conditions when we'd like to generate a program certificate?

FYI, @pdpinch

**Comment by pdpinch** [comment]
> 2. While generating certificates, the task will consider all the course runs whose end date has passed and their certificates haven't been generated yet.

How will we handle self-paced courses, where a user can earn a certificate at any time and doesn't need to wait for the end date to pass?

> Currently, I'm trying to set the proctored exams in edX to check if the grades API respects the status of the Proctored Exam

Let us know if you need help with setting this up. I believe proctored exams are a special case of timed exams -- If I'm correct, I don't think you need to set up proctoring just to test the grade behavior. 

In any case, I still need to discuss the timing of certificates for the DEDP MicroMasters courses, since they like to adjust their grades (a.k.a. "curve" the grades) before releasing. 

>  Are we currently looking into creating Program Certificates too? If yes, What would be the list of conditions when we'd like to generate a program certificate?

That will be next. The only input to program certificates are course certificates.

**Comment by arslanashraf7** [comment]
>How will we handle self-paced courses, where a user can earn a certificate at any time and doesn't need to wait for the end date to pass?

So we have two possible options initially:

1- When we run the task for certificates, we keep it open-ended for all the live course runs and don't check for end dates so anyone having passing grades would have a certificate irrespective of the end date of the course.
2- We introduce a simple flag in course run model, e.g. `immidiate_certificates` so when it's `True` we don't check for end_date and generate certificates right on passing.

> Let us know if you need help with setting this up. I believe proctored exams are a special case of timed exams -- If I'm correct, I don't think you need to set up proctoring just to test the grade behavior.

Correct, I have set these in past, hopefully, won't take long. But I'll reach out if I couldn't get them running.

**Comment by arslanashraf7** [comment]
Update:

>How will we handle self-paced courses, where a user can earn a certificate at any time and doesn't need to wait for the end date to pass?

I've added a self-paced courses flag to determine if we want on-demand certificates for a course run.

I was checking the grades behavior with timed/proctored exams in a course. So, As per my research, the grades API includes proctored grades but doesn't respect proctored/timed in order for a student to be passed overall in a course.

e.g. If a student has achieved passing grades as per the grading system for that course the API will return `passed` for that student even if a student hasn't tried proctored exam or failed in it.

>some courses won't want certificates generated until proctored exam results have been reviewed

@pdpinch, So, In our course grading system with Proctored exams, Is it possible for a student to reach a passing grade % without attempting proctored exams? This depends upon the grading system set up for that specific course.

**Comment by pdpinch** [comment]
> So, In our course grading system with Proctored exams, Is it possible for a student to reach a passing grade % without attempting proctored exams? This depends upon the grading system set up for that specific course.

The course team will decide the grading policy. I expect they will configure it so it is impossible to pass the course without passing the proctored special exam.

**Comment by arslanashraf7** [comment]
This has been deployed and tested, Closing via #722
