### ISSUE TITLE
Registration: validate username against openedx

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#734]
We've seen instances of username conflicts due to an undetermined character set conversion, so we should put some code in place to validate the inputs:

Openedx has an API call to validate the input:

https://courses.edx.org/api-docs/#/user/user_v1_validation_registration_create

When the user submits the form after confirming their email we should make this validation call. We're only concerned about `username` at this time. I'm not sure if other fields are required, but we should ignore error output from them for now.

**Comment by collinpreston** [comment]
@rhysyngsun, what should occur if there if the validation fails (there is a matching username in openedx)?

**Comment by pdpinch** [comment]
Do we have an existing method to display an error message and ask the user to choose something else?

**Comment by collinpreston** [comment]
@pdpinch, yes
![Screen Shot 2022-07-28 at 12 30 09 PM](https://user-images.githubusercontent.com/8311573/181590189-98df2232-863a-4359-8074-31e34d9f4799.png)

**Comment by collinpreston** [comment]
@rhysyngsun @pdpinch , what should occur if `mitxonline` cannot connect to the `openedx` API endpoint?

**Comment by pdpinch** [comment]
The screenshot looks great. If you can make that happen, with that message, that will be good.

**Comment by collinpreston** [comment]
@pdpinch I've set it up so that if `mitxonline` cannot connect to `openedx`, the user account will be created on `mitxonline` and the user will not receive any sort of message.  This is not the same as if `openedx` responds with a non-200 HTTP code, then the user will receive an error message.

I believe this follows suit with our current workflow for which if `mitxonline` is unable to connect to `openedx` during the user registration process, the user is still created in `mitxonline` and allowed to proceed.

**Comment by pdpinch** [comment]
> @pdpinch <https://github.com/pdpinch> I've set it up so that if mitxonline cannot connect to openedx, the user account will be created on mitxonline and the user will not receive any sort of message. This is not the same as if openedx responds with a non-200 HTTP code, then the user will receive an error message.

This makes sense to me. It gives us some time to detect and fix an failure in openedx. It runs the risk of username collisions during the downtime, but we can fix that up manually if/when it comes to it.
