### ISSUE TITLE
flexible pricing: denying a request changes status to "skipped" 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#756]
### Steps to Reproduce

1. with a learner account, make a flexible pricing request that requires manual review
2. as an admin, deny the request through the staff dashboard

### Expected Behavior

1. the request's status is updated to something that matches the button, like "denied"
2. the learner has to pay full price for the course (or contact customer support to reset their request) -- 

NOTE that #2 is what currently happens, so the behavior for the learner is correct. #1 is just confusing for the admin user. 

### Actual Behavior

1. the request's status is updated to "skipped"
2. the learner has to pay full price for the course (or contact customer support to reset their request)

**Comment by jkachel** [comment]
It'd be pretty easy to change the underlying status to "denied" - that would make it match up with the other staff dashboard UI as well as the messaging that goes to the learner if their request hits that status. It'll need to be changed in a couple of places (I think I found 6 using grep in flexiblepricing) and a migration will be needed to change any requests that are in the "skipped" status into "denied". Should be pretty straightforward, though.

We can also change the staff-dashboard UI to use skipped instead of denied. That wouldn't require any database changes and it'd match up with MicroMasters (which is where that status came from) but it'd leave the disconnect with the learner messaging.
