### ISSUE TITLE
Certificates: management command for creating and revoking course certificates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#881]
From time to time, course teams would like to grant, or revoke a certificate manually. 

This will also be useful for manual testing scenarios where we need a certificate. 

#### acceptance criteria

- Inputs:
  - courserun readable_id
  - email (optional; default is to attempt certificates for all _enrolled_ users)
  - grade (optional; overrides the final grade for a single user)
- use the grades method of [edx-api-client](https://github.com/mitodl/edx-api-client/)
- if possible, fetch all the grades and the passed status in one request, instead of iterating through each user
- if the user passed, create a course certificate for them

- also need a way to revoke an existing certificate

**Comment by arslanashraf7** [comment]
Posting an update about the working of the command that's created for this:

**Criteria & Conditions (For operations in the command)**
1. A course run (Course Run's `courseware_id`) is needed for all the operations in the command
2. _Grade override and revoke/un-revoke_ operations are supported for a single user only, so for these operations, the command will specifically need a user
3. The _Create_ operation is supported for single or all users
    1. If a user is provided while running `--create` the operation will run only for that specific user
    2. If a user is not provided while running `--create` the operation will for all the enrolled users

**Overall behavior**
1. The command will not check the eligibility of the course run like the regular 24 hours task for certificates, it will just perform the operation specifically for the provided run
2. In the case of `--grade=` if the grade is greater than `0.0` the command will override the grade and mark the user passed and generate the certificate
3. In case the grade is not provided, the command will check the eligibility criteria of certificates e.g. (Passed in edX + Paid enrollment - `Verified`)

**Samples:**

**Revoke, Un-Revoke (This needs a user, it only works for a single user)**

- `./mange.py manage_certificates —revoke —user=<username or email> —run=<course_run_courseware_id> `(Revokes the user certificate for a specific run)

**Create certificates (This supports single user or multiple users if no user is provided, If a user is provided it runs for that single user only):**

- `./manage.py manage_certificates —create —user=<username or email> —run=<course_run_courseware_id>` (This should create/update the grades for the user and create the certificate for the provided user if the user has passed grade from edX and enrolled in Verified/paid mode)

**Override Grade (This operation needs a user and works only for a single user):**
1. `./manage.py manage_certificates —create —user=<username or email> —run=<course_run_courseware_id> —grade=<a float value between 0.0-1.0>` (This should override the grades for the user with the provided grade in parameters and create the certificate for the provided user regardless of the passing grade and paid enrollment) - This will not create the certificate for the user in the case when `grade=0.0` otherwise it will override the grade+create certificate

**Comment by pdpinch** [comment]
Thanks for the detailed documentation. Can you put it into a how-to post in hq/discussions?

Can this be closed?

**Comment by arslanashraf7** [comment]
> Thanks for the detailed documentation. Can you put it into a how-to post in hq/discussions?
> 
> Can this be closed?

Created the discussion post [here](https://github.com/mitodl/hq/discussions/259).

Also tested it on RC, and this can be closed. Closing it via https://github.com/mitodl/mitxonline/pull/897.
