### ISSUE TITLE
can't refresh staff dashboard

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#940]
### Steps to Reproduce

1. go to https://rc.mitxonline.mit.edu/staff-dashboard/
2. sign in   
3. Click on "Flexible Pricing" to go to https://rc.mitxonline.mit.edu/staff-dashboard/flexible_pricing
4. reload the page

### Expected Behavior

- I'm already logged in to mitxonline.mit.edu and have an active session. I don't know why I need to click "sign in" in step 2.
- The dashboard should refresh without requiring me to click sign in _again_.

### Actual Behavior

- I get the sign in page again. 
- After I sign in, I have to click "Flexible Pricing" again.

**Comment by rhysyngsun** [comment]
I think this has something to do with how I set up the authentication initially and is probably worth revisiting - it's done via the oauth2 login that refine supports, which I opted for because I wanted a simple way of getting authentication up and running without having to deal with the difficulties of the refine app running on a different "host" because of the different port at the time. That's no longer the case though.

I think refine is only storing the session information in-memory - I'd have thought it'd at least put that in session storage also but it appears not.

Additionally it shouldn't really require an oauth2 loop because a staff user already has a session, but that probably requires some minimal introspection on the user's permissions so I'm not sure how straightforward that is.
