### ISSUE TITLE
flexible pricing: clean up justifications in admin 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#956]
As an admin user, not all justifications make sense for all actions. 

#### Acceptance Criteria:

- [ ] For "Approve", the only possible justification is "documents in order" -- if it can't be the only choice, it should at least be the default choice. 
- [ ] Reset doesn't need a justification. Ideally we would clear the justification when the admin resets. We don't need to pick a justification in the pop-up. 
- [ ] "Documents in order" should not be an justification option for "Deny" 

#### Related issues

- We have standardized email macros for all the "Deny" justifications. It would save the admin time to have the the email prepopulate with those standards.

**Comment by collinpreston** [comment]
For bullet #1, what was added in https://github.com/mitodl/mitxonline/pull/781 should be reviewed.

**Comment by rachellougee** [comment]
@pdpinch Since we are displaying all the flexible requests in the dashboard regardless it has already been approved/reset/denied or not, I wanted to clarify the expected functionality here.
- "Approve", does it apply to all statuses regardless if it has been reviewed or not?
   -
   - if a request has already been denied/reset, should we always set it to "Documents in order" in these cases? 
   - In [#781](https://github.com/mitodl/mitxonline/pull/781), it defaults to "Documents in order" when approving a pending order (which has no previous justification), but it doesn't default to "Documents in order" when approving a reset/denied order(It might not be normal workflow).
   
<img width="538" alt="image" src="https://user-images.githubusercontent.com/3138890/189956221-7fd72d0d-5165-4780-811e-680c83b4d467.png">

The same question for reset and deny button, does it apply to all status? (changing from approved to reset/denied, or pending to reset/denied)

**Comment by pdpinch** [comment]
> if a request has already been denied/reset, should we also set it to "Documents in order" when approving in these cases? (It might not be a normal workflow).

I think it's a normal workflow to go from reset to approve, if the user has updated their documentation. In any case, "Documents in Order" should be the default choice, no matter what the prior state is.
